// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaApp.Models.Data;

#nullable disable

namespace Villa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240930232542_seed-data")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa.Models.Villa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81fa35cf-15d1-4f6e-8ed7-0c453839b783"),
                            Amenity = "Private pool, Wi-Fi, Air conditioning",
                            Details = "A spacious villa with an ocean view and modern amenities.",
                            ImageUrl = "https://example.com/luxury-villa.jpg",
                            Name = "Luxury Villa",
                            Occupancy = 6,
                            Rate = 500.0,
                            Sqft = 1500
                        },
                        new
                        {
                            Id = new Guid("cc48e134-0c1e-4107-81d3-b797fc534138"),
                            Amenity = "Fireplace, Outdoor jacuzzi, Hiking access",
                            Details = "A cozy mountain villa surrounded by nature and hiking trails.",
                            ImageUrl = "https://example.com/mountain-retreat.jpg",
                            Name = "Mountain Retreat",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 1200
                        },
                        new
                        {
                            Id = new Guid("6d39f48f-923d-41da-8adb-67e524b6f345"),
                            Amenity = "Rooftop access, Smart home features, High-speed internet",
                            Details = "A modern loft in the heart of the city with stunning skyline views.",
                            ImageUrl = "https://example.com/city-loft.jpg",
                            Name = "City Loft",
                            Occupancy = 2,
                            Rate = 400.0,
                            Sqft = 1000
                        },
                        new
                        {
                            Id = new Guid("2de61ebe-212e-4420-b995-8e431057ba8a"),
                            Amenity = "Beachfront, Barbecue, Sun deck",
                            Details = "A charming beach house with direct access to the shore.",
                            ImageUrl = "https://example.com/beach-house.jpg",
                            Name = "Beach House",
                            Occupancy = 5,
                            Rate = 450.0,
                            Sqft = 1300
                        },
                        new
                        {
                            Id = new Guid("029289e5-db33-4632-9eb6-3e7f120d8039"),
                            Amenity = "Garden, Fireplace, Nature views",
                            Details = "A peaceful cottage in the countryside, perfect for relaxation.",
                            ImageUrl = "https://example.com/countryside-cottage.jpg",
                            Name = "Countryside Cottage",
                            Occupancy = 3,
                            Rate = 280.0,
                            Sqft = 900
                        },
                        new
                        {
                            Id = new Guid("811d2d74-c52b-4bd0-a377-cde0b8dbdb00"),
                            Amenity = "Infinity pool, Outdoor lounge, Desert tours",
                            Details = "A unique villa in the desert with breathtaking views.",
                            ImageUrl = "https://example.com/desert-oasis.jpg",
                            Name = "Desert Oasis",
                            Occupancy = 6,
                            Rate = 550.0,
                            Sqft = 1400
                        },
                        new
                        {
                            Id = new Guid("cf8c51bb-b82d-44c3-850a-903f48c33cc3"),
                            Amenity = "Private garden, Outdoor pool, Hammocks",
                            Details = "A tropical-themed villa surrounded by lush greenery.",
                            ImageUrl = "https://example.com/tropical-paradise.jpg",
                            Name = "Tropical Paradise",
                            Occupancy = 7,
                            Rate = 600.0,
                            Sqft = 1600
                        },
                        new
                        {
                            Id = new Guid("678ced43-4e76-486b-b273-e8f76bcf4fc8"),
                            Amenity = "Ski-in/ski-out, Fireplace, Sauna",
                            Details = "A cozy chalet located near the ski slopes.",
                            ImageUrl = "https://example.com/ski-chalet.jpg",
                            Name = "Ski Chalet",
                            Occupancy = 5,
                            Rate = 480.0,
                            Sqft = 1100
                        },
                        new
                        {
                            Id = new Guid("41b7c09f-d9d6-4a04-bbff-a894380f00b3"),
                            Amenity = "Fire pit, Hiking trails, Wildlife viewing",
                            Details = "A rustic cabin nestled in the heart of the forest.",
                            ImageUrl = "https://example.com/forest-cabin.jpg",
                            Name = "Forest Cabin",
                            Occupancy = 4,
                            Rate = 320.0,
                            Sqft = 950
                        },
                        new
                        {
                            Id = new Guid("61954aa9-f6e3-4a1f-9e1b-ed99f3854e95"),
                            Amenity = "Private elevator, Rooftop pool, City views",
                            Details = "A luxurious penthouse suite in a high-rise building.",
                            ImageUrl = "https://example.com/penthouse-suite.jpg",
                            Name = "Penthouse Suite",
                            Occupancy = 8,
                            Rate = 800.0,
                            Sqft = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
